#!/usr/bin/env perl
use strict;
use warnings;
use File::Temp qw(tempdir);
use FindBin;
use Test::More;

my $fixture = tempdir('local-lock-test.XXXXXX', TMPDIR => 1, CLEANUP => 0);
my $passed;
END {
    if ($passed) { require File::Path; File::Path::remove_tree($fixture); }
    else { warn "Lockfile fixtures retained: $fixture\n"; }
}
my $helper = "$FindBin::Bin/rewrite-local-lock-versions.pl";
sub write_file {
    my ($path, $text) = @_;
    open my $file, '>', "$fixture/$path" or die $!;
    print {$file} $text or die $!;
    close $file or die $!;
}
my $lock = <<'LOCK';
# Generated by Cargo. Keep this comment.
version = 4

[[package]]
name = "app"
version = "0.1.0"
dependencies = [
 "core 0.1.0",
 "core 0.1.0 (registry+https://example.invalid/index)",
]

[[package]]
name = "core"
version = "0.1.0"

[[package]]
name = "core"
version = "0.1.0"
source = "registry+https://example.invalid/index"
checksum = "unchanged"
LOCK
write_file('Cargo.lock', $lock);
sub run {
    my (@args) = @_;
    my $pid = fork(); defined $pid or die $!;
    if (!$pid) {
        open STDOUT, '>', "$fixture/output" or die $!;
        open STDERR, '>', "$fixture/error" or die $!;
        exec $^X, $helper, "$fixture/Cargo.lock", @args;
        die "exec: $!";
    }
    waitpid($pid, 0);
    my $status = $?;
    open my $output, '<', "$fixture/output" or die $!;
    my $text = do { local $/; <$output> };
    return ($status, $text);
}
my ($status, $output) = run('0.1.0', '0.2.0', 'app', 'core');
is($status, 0, 'multiple selected packages accepted');
my $expected = $lock;
$expected =~ s/(name = "(?:app|core)"\nversion = ")0.1.0("\n(?!source))/${1}0.2.0$2/g;
$expected =~ s/"core 0.1.0",/"core 0.2.0",/;
is($output, $expected, 'only local identities and exact references change');
for my $args (
    ['0.1.0', '0.2.0', 'absent'], ['0.1.0', '0.2.0', 'app', 'app'],
    ['0.1.1', '0.2.0', 'app'], ['01.1.0', '0.2.0', 'app'],
    ['0.1.0', '0.2.0-beta', 'app'], ['0.1.0', '0.1.0', 'app'],
) {
    ($status, $output) = run(@$args);
    isnt($status, 0, 'invalid selection rejected');
    is($output, '', 'no partial candidate emitted');
}
write_file('Cargo.lock', $lock . "\n[[package]]\nname = \"app\"\nversion = \"0.1.0\"\n");
($status, $output) = run('0.1.0', '0.2.0', 'app');
isnt($status, 0, 'duplicate local identity rejected');
is($output, '', 'duplicate rejection emits no candidate');

# Let Cargo independently validate transformed real local dependency graphs.
# This fixture needs no registry, builds, commits or consumer metadata writes.
mkdir "$fixture/src" or die $!;
mkdir "$fixture/core" or die $!;
mkdir "$fixture/core/src" or die $!;
write_file('src/lib.rs', "pub fn app() {}\n");
write_file('core/src/lib.rs', "pub fn core() {}\n");
sub manifests {
    my ($version) = @_;
    write_file('Cargo.toml', "[package]\nname = \"app\"\nversion = \"$version\"\nedition = \"2021\"\n[workspace]\nmembers = [\"core\"]\n[dependencies]\ncore = { path = \"core\" }\n");
    write_file('core/Cargo.toml', "[package]\nname = \"core\"\nversion = \"$version\"\nedition = \"2021\"\n");
}
sub cargo {
    my (@args) = @_;
    my $pid = fork(); defined $pid or die $!;
    if (!$pid) {
        chdir $fixture or die $!;
        $ENV{CARGO_NET_OFFLINE} = 'true';
        $ENV{RUSTUP_AUTO_INSTALL} = '0';
        open STDOUT, '>', "$fixture/cargo-output" or die $!;
        open STDERR, '>>', "$fixture/cargo-errors" or die $!;
        exec 'cargo', @args;
        die "cargo exec: $!";
    }
    waitpid($pid, 0);
    return $?;
}
manifests('0.1.0');
unlink "$fixture/Cargo.lock" or die $!;
is(cargo('generate-lockfile', '--offline'), 0, 'Cargo generates local-only fixture');
($status, $output) = run('0.1.0', '0.2.0', 'app', 'core');
is($status, 0, 'real Cargo lockfile transforms');
write_file('Cargo.lock', $output);
manifests('0.2.0');
is(cargo('metadata', '--offline', '--locked', '--format-version', '1'), 0,
    'Cargo accepts exact transformed graph without lock updates');
$passed = Test::More->builder->is_passing;
done_testing;
